### ISSUE TITLE
Could not parse application stylesheet zsh: abort      sudo python rPPG_GUI.py

### ISSUE THREAD

**Issue by tpcmi** [shicaiwei123/anti-spoofing-of-rppg#3]
emmm,学习代码中。。。。
这个咋整呀 😄

**Comment by shicaiwei123** [comment]
这个不影响使用,等一会,就会出现程序运行结果

**Comment by tpcmi** [comment]
可是程序直接终止了



发自我的iPhone


------------------ Original ------------------

**Comment by shicaiwei123** [comment]
改成 python3 rPPPG_GUI.py 呢,加sudo之后好像是会出现其他问题.如果还不可以,检查一下摄像头是否正常工作,或者把完整报错粘贴上来,否则我不好分析...

**Comment by tpcmi** [comment]
我首先是`python rPPG_GUI.py`，出现如下问题：
Traceback (most recent call last):
  File "rPPG_GUI.py", line 32, in <module>
    from rPPG_Extracter import *
  File "/Users/tpcmi/Downloads/anti-spoofing-of-rppg-master/rPPG_Extracter.py", line 10, in <module>
    from FaceDetection import c_face_detection
  File "/Users/tpcmi/Downloads/anti-spoofing-of-rppg-master/FaceDetection.py", line 7, in <module>
    os.seteuid(pwd.getpwnam(os.getlogin()).pw_uid)
PermissionError: [Errno 1] Operation not permitted
---
所以我加上了sudo，出现如下：
Could not parse application stylesheet
zsh: abort      sudo python rPPG_GUI.py
用python3的方式也没有改变
网上查了一下说第一种报错是因为不是root；第二种报错说是Qt里面有什么部分语法问题

**Comment by shicaiwei123** [comment]
有可能是mac的zsh shell的问题....我没在mac系统测试过.但是刚刚我删除了pwd的使用,在本地测试:sudo python3 rPPG_GUI.py 或者python3 rPPG_GUI.py 都没问题...你可以pull最新的再测试一下,如果还不行,再把报错粘贴上来
